rate: 25

estimator_types: [
  "BRICKFLOW",
  "HECTOR",
  "T265",
  "BRICK",
  "VIO",
  "ICP",
  "RTK",
  "OPTFLOWGPS",
  "GPS",
  "OPTFLOW",
  "OTHER",
]

constraints: [
  "slow",
  "medium",
  "fast",
  "darpa",
]

constraint_management:

  # list of allowed gains per odometry mode
  allowed_constraints:
    BRICKFLOW: ["slow", "medium", "fast", "darpa"]
    OPTFLOW: ["slow", "medium", "fast", "darpa"]
    HECTOR: ["slow", "medium", "fast", "darpa"]
    T265: ["slow", "medium", "fast"]
    BRICK: ["slow"]
    VIO: ["slow"]
    ICP: ["slow", "darpa"]
    RTK: ["slow", "medium", "fast", "darpa"]
    OPTFLOWGPS: ["slow", "darpa"]
    GPS: ["slow", "medium", "fast", "darpa"]
    OPTFLOW: ["slow", "medium", "fast", "darpa"]
    OTHER: ["slow"]

  # those gains will be used automatically when a localization mode switches
  # and the current gains are not in the allowed list (next paragraphs)
  fallback_constraints:
    BRICKFLOW: "slow"
    HECTOR: "darpa"
    T265: "slow"
    BRICK: "slow"
    VIO: "slow"
    ICP: "darpa"
    RTK: "medium"
    OPTFLOWGPS: "slow"
    GPS: "medium"
    OPTFLOW: "slow"
    OTHER: "slow"
