location: .gitman
sources:
- name: baca2018model
  type: git
  repo: git@mrs.felk.cvut.cz:papers/iros2018mpc
  sparse_paths:
  -
  rev: master
  link: thesis/papers/baca2018model
  scripts:
  - git submodule update --init --recursive
- name: baca2019autonomous
  type: git
  repo: git@mrs.felk.cvut.cz:papers/mbzirc-landing
  sparse_paths:
  -
  rev: master
  link: thesis/papers/iros2019autonomous
  scripts:
  - git submodule update --init --recursive
- name: baca2019timepix
  type: git
  repo: git@mrs.felk.cvut.cz:papers/iros2019radiation
  sparse_paths:
  -
  rev: master
  link: thesis/papers/baca2019timepix
  scripts:
  - git submodule update --init --recursive
- name: compton_camera_filter
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_filter
  sparse_paths:
  -
  rev: master
  link: ros_packages/compton_camera_filter
  scripts:
  - git submodule update --init --recursive
- name: compton_camera_python
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_python
  sparse_paths:
  -
  rev: master
  link: ros_packages/compton_camera_python
  scripts:
  - git submodule update --init --recursive
- name: gazebo_rad_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_msgs
  sparse_paths:
  -
  rev: master
  link: ros_packages/gazebo_rad_msgs
  scripts:
  - git submodule update --init --recursive
- name: gazebo_rad_source
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_source
  sparse_paths:
  -
  rev: devel
  link: ros_packages/gazebo_rad_source
  scripts:
  - git submodule update --init --recursive
- name: gazebo_timepix
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_timepix
  sparse_paths:
  -
  rev: master
  link: ros_packages/gazebo_timepix
  scripts:
  - git submodule update --init --recursive
- name: geometry_visual_utils
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/geometry_visual_utils.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/geometry_visual_utils
  scripts:
  - git submodule update --init --recursive
- name: petrlik2020robust
  type: git
  repo: git@mrs.felk.cvut.cz:papers/icra2020darpa
  sparse_paths:
  -
  rev: master
  link: thesis/papers/petrlik2020robust
  scripts:
  - git submodule update --init --recursive
- name: petrlik_fusion
  type: git
  repo: git@mrs.felk.cvut.cz:papers/iros2018fusion.git
  sparse_paths:
  -
  rev: master
  link: thesis/papers/petrlik_fusion
  scripts:
  - git submodule update --init --recursive
- name: radiation_utils
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/radiation_utils.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/radiation_utils
  scripts:
  - git submodule update --init --recursive
- name: rviz_visual_tools
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/rviz_visual_tools
  sparse_paths:
  -
  rev: master
  link: ros_packages/rviz_visual_tools
  scripts:
  - git submodule update --init --recursive
- name: spurny2018cooreparive
  type: git
  repo: git@mrs.felk.cvut.cz:papers/mbzirc-treasure-hunt
  sparse_paths:
  -
  rev: master
  link: thesis/papers/spurny2018cooperative
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: baca2018model
  type: git
  repo: git@mrs.felk.cvut.cz:papers/iros2018mpc
  sparse_paths:
  -
  rev: 1ead8f51a31375f6a2916a3f36cd5ff08f83c7aa
  link: thesis/papers/baca2018model
  scripts:
  - git submodule update --init --recursive
- name: baca2019autonomous
  type: git
  repo: git@mrs.felk.cvut.cz:papers/mbzirc-landing
  sparse_paths:
  -
  rev: 6c19cb11e3336db90b9f103c078b197ed3dfb473
  link: thesis/papers/iros2019autonomous
  scripts:
  - git submodule update --init --recursive
- name: baca2019timepix
  type: git
  repo: git@mrs.felk.cvut.cz:papers/iros2019radiation
  sparse_paths:
  -
  rev: 52457132a1a93181642c6bfb7dfdc5535ce7be51
  link: thesis/papers/baca2019timepix
  scripts:
  - git submodule update --init --recursive
- name: compton_camera_filter
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_filter
  sparse_paths:
  -
  rev: ed86d646be2188989126202cf890da475cca8c7b
  link: ros_packages/compton_camera_filter
  scripts:
  - git submodule update --init --recursive
- name: compton_camera_python
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_python
  sparse_paths:
  -
  rev: 7f3b926969672b57a712232ab60285db34c1dd52
  link: ros_packages/compton_camera_python
  scripts:
  - git submodule update --init --recursive
- name: gazebo_rad_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_msgs
  sparse_paths:
  -
  rev: b57ca6b1fe5df88c18d70a9567e59521c362bf90
  link: ros_packages/gazebo_rad_msgs
  scripts:
  - git submodule update --init --recursive
- name: gazebo_rad_source
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_source
  sparse_paths:
  -
  rev: 6a5e97e6582c6f1757789c29b27cb509134b8c18
  link: ros_packages/gazebo_rad_source
  scripts:
  - git submodule update --init --recursive
- name: gazebo_timepix
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_timepix
  sparse_paths:
  -
  rev: 1049791906f1729b38dc5820944bece2e7f625cc
  link: ros_packages/gazebo_timepix
  scripts:
  - git submodule update --init --recursive
- name: geometry_visual_utils
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/geometry_visual_utils.git
  sparse_paths:
  -
  rev: fb1f51571200459d351d739d1bfb251384884d79
  link: ros_packages/geometry_visual_utils
  scripts:
  - git submodule update --init --recursive
- name: petrlik2020robust
  type: git
  repo: git@mrs.felk.cvut.cz:papers/icra2020darpa
  sparse_paths:
  -
  rev: de91db47441202c1cab25f692132d6fc4ab76847
  link: thesis/papers/petrlik2020robust
  scripts:
  - git submodule update --init --recursive
- name: petrlik_fusion
  type: git
  repo: git@mrs.felk.cvut.cz:papers/iros2018fusion.git
  sparse_paths:
  -
  rev: 4c4d5b2105d9c899bd09977b629545f56b8ac191
  link: thesis/papers/petrlik_fusion
  scripts:
  - git submodule update --init --recursive
- name: radiation_utils
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/radiation_utils.git
  sparse_paths:
  -
  rev: bfa2e94cfcaa76c5ed52ad96e735783a05d366a2
  link: ros_packages/radiation_utils
  scripts:
  - git submodule update --init --recursive
- name: rviz_visual_tools
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/rviz_visual_tools
  sparse_paths:
  -
  rev: 277e38f0118e096c9a366ac920129d21fcdbe34b
  link: ros_packages/rviz_visual_tools
  scripts:
  - git submodule update --init --recursive
- name: spurny2018cooreparive
  type: git
  repo: git@mrs.felk.cvut.cz:papers/mbzirc-treasure-hunt
  sparse_paths:
  -
  rev: 903ca4adc55116ba80cd910aaf9ed30154103bd0
  link: thesis/papers/spurny2018cooperative
  scripts:
  - git submodule update --init --recursive
