location: .gitman
sources:
- name: baca2018model
  type: git
  repo: git@mrs.felk.cvut.cz:papers/iros2018mpc
  sparse_paths:
  -
  rev: master
  link: thesis/papers/baca2018model
  scripts:
  - git submodule update --init --recursive
- name: baca2019autonomous
  type: git
  repo: git@mrs.felk.cvut.cz:papers/mbzirc-landing
  sparse_paths:
  -
  rev: master
  link: thesis/papers/iros2019autonomous
  scripts:
  - git submodule update --init --recursive
- name: baca2019timepix
  type: git
  repo: git@mrs.felk.cvut.cz:papers/iros2019radiation
  sparse_paths:
  -
  rev: master
  link: thesis/papers/baca2019timepix
  scripts:
  - git submodule update --init --recursive
- name: compton_camera_filter
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_filter
  sparse_paths:
  -
  rev: master
  link: ros_packages/compton_camera_filter
  scripts:
  - git submodule update --init --recursive
- name: compton_camera_python
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_python
  sparse_paths:
  -
  rev: master
  link: ros_packages/compton_camera_python
  scripts:
  - git submodule update --init --recursive
- name: gazebo_rad_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_msgs
  sparse_paths:
  -
  rev: master
  link: ros_packages/gazebo_rad_msgs
  scripts:
  - git submodule update --init --recursive
- name: gazebo_rad_source
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_source
  sparse_paths:
  -
  rev: master
  link: ros_packages/gazebo_rad_source
  scripts:
  - git submodule update --init --recursive
- name: gazebo_timepix
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_timepix
  sparse_paths:
  -
  rev: master
  link: ros_packages/gazebo_timepix
  scripts:
  - git submodule update --init --recursive
- name: geometry_visual_utils
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/geometry_visual_utils.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/geometry_visual_utils
  scripts:
  - git submodule update --init --recursive
- name: rviz_visual_tools
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/rviz_visual_tools
  sparse_paths:
  -
  rev: master
  link: ros_packages/rviz_visual_tools
  scripts:
  - git submodule update --init --recursive
- name: spurny2018cooreparive
  type: git
  repo: git@mrs.felk.cvut.cz:papers/mbzirc-treasure-hunt
  sparse_paths:
  -
  rev: master
  link: thesis/papers/spurny2018cooperative
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: compton_camera_filter
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_filter
  sparse_paths:
  -
  rev: e84856c79c5404b68a67daaba78c9d3ddc19774b
  link: ros_packages/compton_camera_filter
  scripts:
  - git submodule update --init --recursive
- name: compton_camera_python
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_python
  sparse_paths:
  -
  rev: 34c6e60da4f6e26174831119f349edf560b64a17
  link: ros_packages/compton_camera_python
  scripts:
  - git submodule update --init --recursive
- name: gazebo_rad_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_msgs
  sparse_paths:
  -
  rev: f98c100905a05627bb72d3e27538fe7084020734
  link: ros_packages/gazebo_rad_msgs
  scripts:
  - git submodule update --init --recursive
- name: gazebo_rad_source
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_source
  sparse_paths:
  -
  rev: 7c3077a97a653738ee8bcec563e8eeddc8f34177
  link: ros_packages/gazebo_rad_source
  scripts:
  - git submodule update --init --recursive
- name: gazebo_timepix
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_timepix
  sparse_paths:
  -
  rev: 4946eba45ecc242a1f084d8a58bb541f8dfebb2a
  link: ros_packages/gazebo_timepix
  scripts:
  - git submodule update --init --recursive
- name: geometry_visual_utils
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/geometry_visual_utils.git
  sparse_paths:
  -
  rev: f368fc032795006a9bb4c633c5b4279791ee3703
  link: ros_packages/geometry_visual_utils
  scripts:
  - git submodule update --init --recursive
- name: rviz_visual_tools
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/rviz_visual_tools
  sparse_paths:
  -
  rev: 277e38f0118e096c9a366ac920129d21fcdbe34b
  link: ros_packages/rviz_visual_tools
  scripts:
  - git submodule update --init --recursive
