location: .gitman
sources:
- name: baca2018model
  type: git
  repo: git@mrs.felk.cvut.cz:papers/iros2018mpc
  sparse_paths:
  -
  rev: master
  link: thesis/papers/baca2018model
  scripts:
  - git submodule update --init --recursive
- name: baca2019autonomous
  type: git
  repo: git@mrs.felk.cvut.cz:papers/mbzirc-landing
  sparse_paths:
  -
  rev: master
  link: thesis/papers/iros2019autonomous
  scripts:
  - git submodule update --init --recursive
- name: baca2019timepix
  type: git
  repo: git@mrs.felk.cvut.cz:papers/iros2019radiation
  sparse_paths:
  -
  rev: master
  link: thesis/papers/baca2019timepix
  scripts:
  - git submodule update --init --recursive
- name: compton_camera_filter
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_filter
  sparse_paths:
  -
  rev: master
  link: ros_packages/compton_camera_filter
  scripts:
  - git submodule update --init --recursive
- name: compton_camera_python
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_python
  sparse_paths:
  -
  rev: master
  link: ros_packages/compton_camera_python
  scripts:
  - git submodule update --init --recursive
- name: gazebo_rad_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_msgs
  sparse_paths:
  -
  rev: master
  link: ros_packages/gazebo_rad_msgs
  scripts:
  - git submodule update --init --recursive
- name: gazebo_rad_source
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_source
  sparse_paths:
  -
  rev: master
  link: ros_packages/gazebo_rad_source
  scripts:
  - git submodule update --init --recursive
- name: gazebo_timepix
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_timepix
  sparse_paths:
  -
  rev: master
  link: ros_packages/gazebo_timepix
  scripts:
  - git submodule update --init --recursive
- name: geometry_visual_utils
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/geometry_visual_utils.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/geometry_visual_utils
  scripts:
  - git submodule update --init --recursive
- name: petrlik2020robust
  type: git
  repo: git@mrs.felk.cvut.cz:papers/icra2020darpa
  sparse_paths:
  -
  rev: master
  link: thesis/papers/petrlik2020robust
  scripts:
  - git submodule update --init --recursive
- name: rviz_visual_tools
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/rviz_visual_tools
  sparse_paths:
  -
  rev: master
  link: ros_packages/rviz_visual_tools
  scripts:
  - git submodule update --init --recursive
- name: spurny2018cooreparive
  type: git
  repo: git@mrs.felk.cvut.cz:papers/mbzirc-treasure-hunt
  sparse_paths:
  -
  rev: master
  link: thesis/papers/spurny2018cooperative
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: baca2018model
  type: git
  repo: git@mrs.felk.cvut.cz:papers/iros2018mpc
  sparse_paths:
  -
  rev: 1ead8f51a31375f6a2916a3f36cd5ff08f83c7aa
  link: thesis/papers/baca2018model
  scripts:
  - git submodule update --init --recursive
- name: baca2019autonomous
  type: git
  repo: git@mrs.felk.cvut.cz:papers/mbzirc-landing
  sparse_paths:
  -
  rev: 6c19cb11e3336db90b9f103c078b197ed3dfb473
  link: thesis/papers/iros2019autonomous
  scripts:
  - git submodule update --init --recursive
- name: baca2019timepix
  type: git
  repo: git@mrs.felk.cvut.cz:papers/iros2019radiation
  sparse_paths:
  -
  rev: ec9f6608ee0ecb12650d112a655df233e7dca819
  link: thesis/papers/baca2019timepix
  scripts:
  - git submodule update --init --recursive
- name: compton_camera_filter
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_filter
  sparse_paths:
  -
  rev: f9939781b72af02c9c21aa023efc95ffe6c72533
  link: ros_packages/compton_camera_filter
  scripts:
  - git submodule update --init --recursive
- name: compton_camera_python
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_python
  sparse_paths:
  -
  rev: 34c6e60da4f6e26174831119f349edf560b64a17
  link: ros_packages/compton_camera_python
  scripts:
  - git submodule update --init --recursive
- name: gazebo_rad_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_msgs
  sparse_paths:
  -
  rev: f98c100905a05627bb72d3e27538fe7084020734
  link: ros_packages/gazebo_rad_msgs
  scripts:
  - git submodule update --init --recursive
- name: gazebo_rad_source
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_source
  sparse_paths:
  -
  rev: 7c3077a97a653738ee8bcec563e8eeddc8f34177
  link: ros_packages/gazebo_rad_source
  scripts:
  - git submodule update --init --recursive
- name: gazebo_timepix
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_timepix
  sparse_paths:
  -
  rev: 4946eba45ecc242a1f084d8a58bb541f8dfebb2a
  link: ros_packages/gazebo_timepix
  scripts:
  - git submodule update --init --recursive
- name: geometry_visual_utils
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/geometry_visual_utils.git
  sparse_paths:
  -
  rev: f368fc032795006a9bb4c633c5b4279791ee3703
  link: ros_packages/geometry_visual_utils
  scripts:
  - git submodule update --init --recursive
- name: petrlik2020robust
  type: git
  repo: git@mrs.felk.cvut.cz:papers/icra2020darpa
  sparse_paths:
  -
  rev: 6bdc4ee615f835b4f4208268304c3f3e4da74533
  link: thesis/papers/petrlik2020robust
  scripts:
  - git submodule update --init --recursive
- name: rviz_visual_tools
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/rviz_visual_tools
  sparse_paths:
  -
  rev: 0cd0954e7acfc154d1ca23ea058b400a6bd27725
  link: ros_packages/rviz_visual_tools
  scripts:
  - git submodule update --init --recursive
- name: spurny2018cooreparive
  type: git
  repo: git@mrs.felk.cvut.cz:papers/mbzirc-treasure-hunt
  sparse_paths:
  -
  rev: 903ca4adc55116ba80cd910aaf9ed30154103bd0
  link: thesis/papers/spurny2018cooperative
  scripts:
  - git submodule update --init --recursive
