location: .gitman
sources:
- name: gazebo_rad_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_msgs
  sparse_paths:
  -
  rev: master
  link: ros_packages/gazebo_rad_msgs
  scripts:
  - git submodule update --init --recursive
- name: compton_camera_filter
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_filter
  sparse_paths:
  -
  rev: master
  link: ros_packages/compton_camera_filter
  scripts:
  - git submodule update --init --recursive
- name: compton_camera_filter
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/compton_camera_python
  sparse_paths:
  -
  rev: master
  link: ros_packages/compton_camera_python
  scripts:
  - git submodule update --init --recursive
- name: gazebo_rad_source
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_rad_source
  sparse_paths:
  -
  rev: master
  link: ros_packages/gazebo_rad_source
  scripts:
  - git submodule update --init --recursive
- name: gazebo_timepix
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/gazebo_timepix
  sparse_paths:
  -
  rev: master
  link: ros_packages/gazebo_timepix
  scripts:
  - git submodule update --init --recursive
- name: rviz_visual_tools
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/rviz_visual_tools
  sparse_paths:
  -
  rev: master
  link: ros_packages/rviz_visual_tools
  scripts:
  - git submodule update --init --recursive
- name: geometry_visual_utils
  type: git
  repo: git@mrs.felk.cvut.cz:radiation/geometry_visual_utils.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/geometry_visual_utils
  scripts:
  - git submodule update --init --recursive
