name: simulation
root: ./
startup_window: optimizer
pre_window: export UAV_NAME=uav1; export UAV_TYPE=t650
windows:
  - roscore:
      layout: even-vertical
      panes:
        - roscore
  - gazebo:
      layout: even-vertical
      panes:
        - waitForRos; roslaunch mrs_simulation simulation.launch gui:=true
  - rviz:
      layout: even-vertical
      panes:
        - waitForRos; roslaunch radiation_simulation rviz.launch
        - waitForRos; roslaunch mrs_rviz_plugins rviz_interface.launch
  - spawn:
      layout: even-vertical
      panes:
        - waitForSimulation; rosrun mrs_simulation spawn 1 --$UAV_TYPE --run --delete --enable-rangefinder --enable-ground-truth
  - control:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav1; waitForOdometry; roslaunch mrs_uav_general core.launch WORLD_FILE:=./world.yaml config_control_manager:=./custom_configs/control_manager.yaml
  - compton_camera:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav1; waitForRos; roslaunch compton_camera_python compton_camera_1.launch
  - compton_filter:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav1; waitForRos; roslaunch compton_camera_filter compton_filter_1.launch
  - optimizer:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav1; waitForRos; roslaunch compton_camera_filter optimizer_1.launch
  - planner:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav1; waitForRos; read; roslaunch compton_camera_filter trajectory_planner_1.launch
  - plotter:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav1; waitForRos; roslaunch compton_camera_python compton_plotter_1.launch
  - takeoff:
      layout: even-vertical
      panes:
        #{ uav1
        - 'waitForControl;
          export UAV_NAME=uav1;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          sleep 2;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        - export UAV_NAME=uav1; waitForRos; roslaunch mrs_uav_general automatic_start.launch
        #}
  - gazebo_camera_follow:
      layout: even-vertical
      panes:
        - waitForOdometry; gz camera -c gzclient_camera -f uav1; history -s gz camera -c gzclient_camera -f uav1
        - waitForOdometry; ~/.i3/layout_manager.sh ./layout.json
